const express = require('express');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai');
const rateLimit = require('express-rate-limit');
const NodeCache = require('node-cache');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json());

// Set up Cache (Standard TTL: 1 hour)
const aiCache = new NodeCache({ stdTTL: 3600, checkperiod: 600 });

// Global Rate Limiter (Basic protection)
const globalLimiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 200, // Limit each IP to 200 requests per window
    message: { error: "Too many requests from this IP, please try again after 15 minutes." }
});
app.use(globalLimiter);

// Strict Rate Limiter for AI endpoints to protect Gemini Free Tier (15 RPM total)
// We allow max 5 requests per minute per user to be safe.
const aiLimiter = rateLimit({
    windowMs: 60 * 1000, // 1 minute
    max: 5, 
    message: { error: "Noor Buddy is receiving too many questions from you right now. Please wait a minute to avoid overloading the system." }
});

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const systemInstruction = `You are Noor Buddy, an authentic Islamic AI companion. 
Your goal is to answer questions strictly according to mainstream, authentic Sunni Islam.
When a user asks a question, you must search your knowledge of the Quran and authentic Hadith (Sahih al-Bukhari, Sahih Muslim, Abu Dawud, Tirmidhi, Nasai, Ibn Majah, etc.).
CRITICAL RULE: Do NOT put citations inline. You MUST gather all your sources and list them clearly at the very bottom of your response under a "Sources:" heading. Ensure your writing is concise and you NEVER repeat the same sentences or points. Do NOT hallucinate sources. If you are unsure, say you do not know.
Keep your tone friendly, respectful, and encouraging. Keep responses relatively short and readable.`;

app.post('/api/chat', aiLimiter, async (req, res) => {
    try {
        const { message, history, userContext } = req.body;
        
        if (!process.env.GEMINI_API_KEY) {
            return res.status(500).json({ error: "Gemini API Key is not configured on the server." });
        }

        // Format history for Gemini
        const formattedHistory = history.map(msg => ({
            role: msg.role === 'ai' ? 'model' : 'user',
            parts: [{ text: msg.text }]
        }));
        
        let personalizedInstruction = systemInstruction;
        if (userContext) {
            personalizedInstruction += `\n\nUSER CONTEXT: You are currently talking to a user named ${userContext.name}. They are currently on a ${userContext.streak}-day streak of using Noor AI. Congratulate them if appropriate, and occasionally address them by their name to make the conversation feel personal.`;
        }

        const chat = ai.chats.create({
            model: 'gemini-2.5-flash',
            config: {
                systemInstruction: personalizedInstruction,
                temperature: 0.2, // Low temperature for factual religious answers
            }
        });

        const fullPrompt = history.map(msg => `${msg.role === 'ai' ? 'Noor Buddy' : 'User'}: ${msg.text}`).join('\n') + `\nUser: ${message}\nNoor Buddy:`;

        // Check Cache
        const cacheKey = `chat_${Buffer.from(fullPrompt).toString('base64').substring(0, 50)}`;
        const cachedResponse = aiCache.get(cacheKey);
        if (cachedResponse) {
            console.log("Serving chat from cache!");
            return res.json({ text: cachedResponse });
        }

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: fullPrompt,
            config: {
                systemInstruction: personalizedInstruction,
                temperature: 0.2
            }
        });

        aiCache.set(cacheKey, response.text);
        res.json({ text: response.text });
    } catch (error) {
        console.error("AI Error:", error);
        if (error.status === 429 || (error.message && error.message.includes('429'))) {
            return res.status(429).json({ error: "Noor Buddy is currently experiencing very high traffic! Please wait a minute and try again." });
        }
        res.status(500).json({ error: "Failed to generate response." });
    }
});

app.post('/api/hifz-check', aiLimiter, async (req, res) => {
    try {
        const { targetText, transcript } = req.body;
        
        if (!process.env.GEMINI_API_KEY) {
            return res.status(500).json({ error: "Gemini API Key is not configured." });
        }

        const prompt = `You are an expert Quran Hifz teacher.
I will provide the target Arabic text (what the student is supposed to recite) and the transcript of what the student actually recited (generated by Speech-to-Text).
Keep in mind that Speech-to-Text for Arabic can sometimes mishear words slightly (e.g. dropping a tashkeel, confusing similar sounding letters). Be lenient on minor STT artifacts, but strict on missing words, skipped words, or completely wrong roots.

Target Text: "${targetText}"
Student Transcript: "${transcript}"

Analyze the transcript against the target text.
Respond ONLY with a valid JSON object matching this schema:
{
  "isCorrect": boolean, // True if they recited it correctly or mostly correctly (allowing for minor STT artifacts). False if they missed words or made major mistakes.
  "feedback": "string", // If incorrect, write exactly what they missed or got wrong in English. Keep it brief. If correct, say 'Perfect, mashaAllah!'
  "wrongWord": "string" // The first Arabic word they got wrong from the Target Text. Null if correct.
}
`;

        // Check Cache
        const cacheKey = `hifz_${targetText}_${transcript}`;
        const cachedResponse = aiCache.get(cacheKey);
        if (cachedResponse) {
            console.log("Serving hifz check from cache!");
            return res.json(cachedResponse);
        }

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                temperature: 0.1,
                responseMimeType: "application/json"
            }
        });

        const jsonMatch = response.text.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
            const parsedData = JSON.parse(jsonMatch[0]);
            aiCache.set(cacheKey, parsedData);
            res.json(parsedData);
        } else {
            res.status(500).json({ error: "Invalid JSON from AI" });
        }
    } catch (error) {
        console.error("Hifz Check Error:", error);
        if (error.status === 429 || (error.message && error.message.includes('429'))) {
            return res.status(429).json({ error: "The grading engine is currently experiencing very high traffic! Please wait a minute and try again." });
        }
        res.status(500).json({ error: "Failed to verify hifz." });
    }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Noor AI Backend running on port ${PORT}`);
});
